Add API to show error messages from failed token fetches
w3c-fedid/FedCM pull request #498
Opened 2023-08-30 21:40 UTC by npm1

2023-08-31 15:17 UTC, yi-gu commented on spec/index.bs
> +    1. Otherwise, return |credential| (this may throw since it may be an
Since we only throw `IdentityCredentialError` post user permission, should we note that `delayException` should be false?

2023-08-31 15:17 UTC, yi-gu commented on spec/index.bs
> +        1. The [=user agent=] MUST show UI to the user indicating that the identity assertion fetch
Should this be MAY instead of MUST given that the Error API is optional for UA?

2023-08-31 15:17 UTC, yi-gu commented on spec/index.bs
> +        1. The [=user agent=] MAY use the {{IdentityCredentialError/url}} to display a hyperlink
Should we use more generic terms for "hyperlink" to allow UA to use different UI affordance to proceed to the url?

2023-08-31 15:17 UTC, yi-gu commented on spec/index.bs
> +            dismissed by the user.
s/dismissed/closed to cover the "acknowledged" part.

2023-08-31 15:17 UTC, yi-gu commented on spec/index.bs
> +    1. If |tokenUrl| is failure:
How would `tokenUrl` be failure? I think we should have validated all the urls after fetching the manifest from configURL.

2023-08-31 15:17 UTC, yi-gu commented on spec/index.bs
> +dictionary IdentityCredentialErrorInit {
Why do we need "Init" in the idl?

2023-09-01 15:43 UTC, npm1 commented on spec/index.bs
> +    1. Otherwise, return |credential| (this may throw since it may be an
No, this is handled separately as we do not return a pair in this case.

2023-09-01 15:52 UTC, npm1 commented on spec/index.bs
> +        1. The [=user agent=] MUST show UI to the user indicating that the identity assertion fetch
Isn't the whole point of this API to ensure error UI is shown? That is what Chrome intends to ship, we should only make this optional if other vendors feel they do not want to show these errors.

2023-09-01 15:52 UTC, npm1 commented on spec/index.bs
> +        1. The [=user agent=] MAY use the {{IdentityCredentialError/url}} to display a hyperlink
Hyperlink is generic and not tied to a specific UI.

2023-09-01 15:52 UTC, npm1 commented on spec/index.bs
> +    1. If |tokenUrl| is failure:
It seems that is not the case right now. Filed https://github.com/fedidcg/FedCM/issues/499 but I will not fix that in this PR.

2023-09-01 15:52 UTC, npm1 commented on spec/index.bs
> +dictionary IdentityCredentialErrorInit {
Because it should not be the same as the exception name?

2023-09-01 15:53 UTC, npm1 commented
Ready for another look @yi-gu

2023-09-01 16:16 UTC, yi-gu approved these changes
Thanks. LGTM!

2023-09-01 16:20 UTC, npm1 commented
Hey @bvandersloot-mozilla @martinthomson @cboozar requesting Mozilla to take a look.

2023-09-06 14:44 UTC, cbiesinger commented on spec/index.bs
> +            <a for="global object">realm</a> and "IdentityCredentialError", and return.
If both exist, should error's code be used for the IdentityCredentialError constructor?

2023-09-06 14:44 UTC, cbiesinger commented on spec/index.bs
> +                {{IdentityCredentialError}} given |globalObject|'s <a for="global object">realm</a>
why does this use an IdentityCredentialError...

2023-09-06 14:44 UTC, cbiesinger commented on spec/index.bs
> +            1. If |json|[|error|] is not an [=ordered map=], set |credential| to failure and return.
...but this sets credential to failure?

2023-09-11 08:40 UTC, npm1 commented on spec/index.bs
> +    constructor(optional DOMString message = "", optional IdentityCredentialErrorInit options = {});
Moving up

2023-09-11 08:40 UTC, npm1 commented on spec/index.bs
> +    readonly attribute DOMString code;
I want to allow the IDP to use their own codes even if they do not mean anything to the user agent and they result in the generic error UI.

2023-09-11 08:40 UTC, npm1 commented on spec/index.bs
> +            <a for="global object">realm</a> and "IdentityCredentialError", and return.
Hmm maybe. I thought of this one as developer error: should token be trusted or error?

2023-09-11 08:40 UTC, npm1 commented on spec/index.bs
> +                {{IdentityCredentialError}} given |globalObject|'s <a for="global object">realm</a>
We now only allow returning IdentityCredential or this kind of error

2023-09-11 08:40 UTC, npm1 commented on spec/index.bs
> +            1. If |json|[|error|] is not an [=ordered map=], set |credential| to failure and return.
Missed this one

2023-09-18 20:25 UTC, cbiesinger approved these changes
Thanks, lgtm

2023-10-04 19:06 UTC, cbiesinger commented on spec/index.bs
> +    1. If |requireSameOrigin| is false and |manifestUrl|'s <a spec=url>domain</a> is not equal to
Shouldn't we use the registrable domain here? https://url.spec.whatwg.org/#host-registrable-domain

2023-10-04 20:40 UTC, npm1 commented on spec/index.bs
> +    1. If |requireSameOrigin| is false and |manifestUrl|'s <a spec=url>domain</a> is not equal to
Done

2023-10-12 02:56 UTC, TallTed requested changes

2023-10-12 02:56 UTC, TallTed commented on spec/index.bs
> +    {{IdentityCredentialErrorInit}} |options| must run the following steps:
```suggestion
Given a |realm|, a {{DOMString}} |message|, and an {{IdentityCredentialErrorInit}}
|options|, the {{IdentityCredentialError/constructor()}} must run the following steps:
```

2023-10-12 02:56 UTC, TallTed commented on spec/index.bs
> +        if it is present in |options|, or to "" otherwise.
```suggestion
    1. If |options|.{{IdentityCredentialError/code}} is present in |options|,
       set <a>this</a>.{{IdentityCredentialError/code}} to it; otherwise, set
       <a>this</a>.{{IdentityCredentialError/code}} to "".
    1. If |options|.{{IdentityCredentialError/url}} is present in |options|,
       set <a>this</a>.{{IdentityCredentialError/url}} to it; otherwise, set
       <a>this</a>.{{IdentityCredentialError/url}} to "".
```

2023-10-12 02:56 UTC, TallTed commented on spec/index.bs
> +    ::  The {{IdentityCredentialError/code}}'s attribute getter returns the value it is set to.
```suggestion
    ::  The {{IdentityCredentialError/code}}'s attribute getter returns the value to which it is set.
```

2023-10-12 02:56 UTC, TallTed commented on spec/index.bs
> +    ::  The {{IdentityCredentialError/url}}'s attribute getter returns the value it is set to.
```suggestion
    ::  The {{IdentityCredentialError/url}}'s attribute getter returns the value to which it is set.
```

2023-10-12 02:56 UTC, TallTed commented on spec/index.bs
> +        1. Otherwise, i.e. if |json|[|error|] [=map/exists=]:
```suggestion
        1. Otherwise (i.e., if |json|[|error|] [=map/exists=]):
```

2024-01-19 16:45 UTC, bvandersloot-mozilla commented on spec/index.bs
> +    readonly attribute DOMString code;
This overwrites a deprecated value that should be `0`. Another name would be good.

2024-01-25 20:04 UTC, npm1 commented on spec/index.bs
> +    readonly attribute DOMString code;
Ah, good catch! We missed that... here are some other naming options, any preference?

- errorCode
- serverError{Code} (eg with or without Code)
- idpError{Code}
- credentialError{Code}

2024-01-25 20:18 UTC, npm1 commented on spec/index.bs
> +    readonly attribute DOMString code;
- error

2024-02-27 19:55 UTC, samuelgoto commented
@npm1 just checking: is there anything else we need to act on before we merge this?

2024-02-27 20:10 UTC, npm1 commented
> @npm1 just checking: is there anything else we need to act on before we merge this?

Yes, I need to rebase and change the `code` to whatever we agree on (awaiting @bvandersloot-mozilla's confirmation about whether `error` is acceptable)

2024-05-24 14:44 UTC, npm1 commented on spec/index.bs
> +    readonly attribute DOMString code;
Ping, I'd like to merge this sooner rather than later especially if we want to make a naming change here.

2024-07-30 15:50 UTC, bvandersloot-mozilla commented on spec/index.bs
> +    readonly attribute DOMString code;
error is good. credentialErrorCode may be better

2024-07-31 15:05 UTC, bvandersloot-mozilla requested changes
I don't think we need to make this web-observable and doing so risks leaking information to the RP about shared browser state.

2024-07-31 21:05 UTC, npm1 commented
> I don't think we need to make this web-observable and doing so risks leaking information to the RP about shared browser state.

What is 'this'? And can you elaborate on the leak you are thinking about?

2024-08-01 11:54 UTC, bvandersloot-mozilla commented
"this" is the `IdentityCredentialError` itself, particularly the `code` variable which contains an unspecified string (presumably one of "invalid_request", "unauthorized_client", "access_denied", "server_error", and "temporarily_unavailable"). If I understand this patch correctly, that ends up returned from `navigator.credentials.get` and reveals internal information about the credential discovery to the RP.

2024-08-01 15:05 UTC, bvandersloot-mozilla commented
Ah, I didn't realize this is happening on the id assertion endpoint only. In that case, this is reasonable, but we should probably enumerate the possible values for `code` and specify when they are returned.

2024-08-01 15:50 UTC, npm1 commented
> Ah, I didn't realize this is happening on the id assertion endpoint only. In that case, this is reasonable, but we should probably enumerate the possible values for `code` and specify when they are returned.

I was hoping to leave the values for `error` (previously `code`) unspecified similar to how we do not specify the format/return of `token`. That way the IdP can send the information needed for the RP to process the error, and the user agent may choose to show generic UI or show more specific UI if it chooses to do so based on the error string. What do you think? I did mention the strings Chrome uses to show more specific UI in case it is of interest for an implementor to match.

2024-08-02 16:08 UTC, TallTed requested changes
Small tweaks for clarity

2024-08-02 16:08 UTC, TallTed commented on spec/index.bs
> +    1. Otherwise, return |credential| (this may throw since it may be an
```suggestion
    1. Otherwise, return |credential| (this may throw, since it may be an
```

2024-08-02 16:08 UTC, TallTed commented on spec/index.bs
>      1. Otherwise, if |accountsList|'s size is 1:
Two "otherwise" at the same level is confusing.

2024-08-02 16:08 UTC, TallTed commented on spec/index.bs
> +            closed by the user.
Nest the note about the wait in the step with the wait, not in its superior.
```suggestion
        1. Wait until the UI is acknowledged or dismissed by the user.  
           Note: this wait means the [=user agent=] rejects the call only after the UI has been
           closed by the user.
```

2024-08-02 16:08 UTC, TallTed commented on spec/index.bs
> +                "IdentityCredentialError" and return.
```suggestion
                "IdentityCredentialError", and return.
```

2024-08-06 22:03 UTC, npm1 commented on spec/index.bs
>      1. Otherwise, if |accountsList|'s size is 1:
Changed to else if, which is arguably less confusing.

2024-08-07 18:45 UTC, TallTed commented on spec/index.bs
>      1. Otherwise, if |accountsList|'s size is 1:
I think this will need revisiting. I don't think the global replace of "otherwise" with "else" resolves my concern, since there are still two of them at the same nesting level.

I think the if/then/else nesting should be more carefully considered: definitely with some nest demotions; probably with some nest promotions; and possibly making some `ol` into `ul` and/or vice versa.

2024-08-08 17:48 UTC, npm1 commented on spec/index.bs
>      1. Otherwise, if |accountsList|'s size is 1:
I have updated the PR to use a switch style, let me know if you think that is clearer. That said, note that having conditional statements like this is accepted, as this is an algorithm, not pure prose. https://infra.spec.whatwg.org/#algorithm-conditional-statements

2024-08-09 16:45 UTC, TallTed commented on spec/index.bs
>      1. Otherwise, if |accountsList|'s size is 1:
Ugh. I see that [one of the examples in the linked section](https://infra.spec.whatwg.org/#algorithm-conditional-statements) looks like what was being done here. I maintain that it is confusing, and has strong potential to lead to problems in implementation and interop, which seem worth avoiding.

Happily, the rendered "switch" style seems likely to reduce if not eliminate those potential problems.

2024-09-19 15:27 UTC, npm1 commented
Rebased this PR in case people want to take another look ahead of TPAC discussion

2025-06-10 16:33 UTC, wseltzer commented
Discussed 10 June [miniutes](https://github.com/w3c-fedid/meetings/blob/main/2025/2025-06-10-FedCM-notes.md)

2025-06-10 22:04 UTC, npm1 commented
Rebased and added a comment regarding error being exposed to the RP. @yi-gu PTAL?

2025-06-11 19:06 UTC, cbiesinger commented on spec/index.bs
> +        An [=IDP=] MUST not expose sensitive user information in this field, since it is exposed to
```suggestion
        An [=IDP=] MUST NOT expose sensitive user information in this field, since it is exposed to
```

2025-06-11 19:08 UTC, cbiesinger commented on spec/index.bs
> +        1. Let |delayException| be the value of the second element of the pair.
Why did you invert the meaning of this parameter? It doesn't look like you changed the callers?

2025-06-11 19:10 UTC, TallTed requested changes

2025-06-11 19:10 UTC, TallTed commented on spec/index.bs
> +        An [=IDP=] MUST not expose sensitive user information in this field, since it is exposed to
```suggestion
        An [=IDP=] MUST NOT expose sensitive user information in this field, since it is exposed to
```

2025-06-11 19:10 UTC, TallTed commented on spec/index.bs
> +    1. <dfn for="create identity credential">Show accounts</dfn> step: if |allAccounts| is not [=list/empty=], also add UI to present the account options to the user.
```suggestion
    1. <dfn for="create identity credential">Show accounts</dfn> step: if |allAccounts|
       is not [=list/empty=], also add UI to present the account options to the user.
```

2025-06-11 19:10 UTC, TallTed commented on spec/index.bs
> +        1. If one of the previous two steps threw an exception, set |credential| to a new {{IdentityCredentialError}} given |globalObject|'s
```suggestion
        1. If one of the previous two steps threw an exception, set |credential| to a new
           {{IdentityCredentialError}} given |globalObject|'s
```

2025-06-11 19:12 UTC, cbiesinger commented on spec/index.bs
> +            "temporarily_unavailable", the [=user agent=] may note the reason in a user-friendly
hmm I don't love the way this is specified. Have you considered something like `The user agent SHOULD support displaying a user-readable message for "invalid_request", "unauthorized_client", "access_denied", "server_error", and "temporarily_unavailable"`?

2025-06-11 19:19 UTC, cbiesinger commented on spec/index.bs
> +Given a |realm|, a {{DOMString}} |message|, and an {{IdentityCredentialErrorInit}} |options|, the
This PR assumes that |options| is optional, but this algorithm does not say so, it probably should? Alternatively the callers should specify an empty dict.

2025-06-11 19:20 UTC, cbiesinger commented on spec/index.bs
> +            [=global object/realm=].
this needs to specify the message argument

2025-06-11 19:21 UTC, cbiesinger commented on spec/index.bs
> +    1. If |requireSameOrigin| is false and |manifestUrl|'s [=url/host=]'s [=host/registrable domain=]
seems like it should be called requireSameSite, not requireSameOrigin

2025-06-11 19:23 UTC, cbiesinger commented on spec/index.bs
> +                1. Let |errorUrl| be the result of [=computing the manifest URL=] given |provider|,
this does not sound right. shouldn't the error URL be relative to the id assertion endpoint, not the config URL?

2025-06-11 21:18 UTC, npm1 commented on spec/index.bs
> +Given a |realm|, a {{DOMString}} |message|, and an {{IdentityCredentialErrorInit}} |options|, the
The fact they are optional is in the idl. When invoked, default value is passed if needed. Example: https://webidl.spec.whatwg.org/#dom-domexception-domexception

2025-06-11 21:18 UTC, npm1 commented on spec/index.bs
> +        1. Let |delayException| be the value of the second element of the pair.
Ah this used to be a bug in the spec but it is fixed so undoing this

2025-06-11 21:18 UTC, npm1 commented on spec/index.bs
> +            "temporarily_unavailable", the [=user agent=] may note the reason in a user-friendly
That would make it normatively required to support these. These are arbitrary enough that I do not want to make this required. I'm only listing these so other user agents know the ones we currently show custom messages for.

2025-06-11 21:18 UTC, npm1 commented on spec/index.bs
> +                1. Let |errorUrl| be the result of [=computing the manifest URL=] given |provider|,
Oh looks like that is how we implemented. That is surprising to me given all other urls were relative to the config url.

2025-06-11 21:18 UTC, npm1 commented on spec/index.bs
> +    1. If |requireSameOrigin| is false and |manifestUrl|'s [=url/host=]'s [=host/registrable domain=]
? No, it was same origin, we only check same site when it was false. But I removed this

2025-06-11 21:19 UTC, npm1 commented on spec/index.bs
> +            [=global object/realm=].
It doesnt?

2025-06-11 21:21 UTC, npm1 commented on spec/index.bs
> +            [=global object/realm=].
Hmm actually maybe it does, the fact they are optional in the IDL might not mean they are optional in here. Not sure

2025-06-11 21:36 UTC, cbiesinger approved these changes

2025-06-11 21:36 UTC, cbiesinger commented on spec/index.bs
> +            "temporarily_unavailable", the [=user agent=] may note the reason in a user-friendly
That's why I said SHOULD and not MUST. or even MAY...

2025-06-11 21:36 UTC, cbiesinger commented on spec/index.bs
> +            [=global object/realm=].
Even if it really is optional, which I am also unsure about, why are you specifying "IdentityCredentialError" everywhere else but using a default "" here?

2025-06-11 21:36 UTC, cbiesinger commented on spec/index.bs
> +                1. Let |errorUrl| be the result of [=computing the manifest URL=] given |provider|,
Usually relative URLs are supposed to be relative to the file they are in, in this case that's the ID assertion endpoint.

The other URLs are in the config file so they are relative to that.

Hmm, I see that we don't support relative URLs for continue_on in the spec :(

2025-06-11 21:36 UTC, cbiesinger commented on spec/index.bs
> +<xmp class="idl">
why is this using xmp but the interface right below is using pre?

2025-06-11 21:36 UTC, cbiesinger commented on spec/index.bs
> +throwing the exception.
is the `delay throwing` change correct? (even if it is, seems unrelated?)

2025-06-11 21:36 UTC, cbiesinger commented on spec/index.bs
> +        1. Otherwise, if {{IdentityAssertionResponse/token}} was specified, let |tokenString|
hmm we should mention somewhere that this should only happen for successful HTTP responses (200 OK).... though this is a pre-existing bug

2025-06-11 22:14 UTC, npm1 commented on spec/index.bs
> +throwing the exception.
Agh, nope

2025-06-11 22:15 UTC, npm1 commented on spec/index.bs
> +            "temporarily_unavailable", the [=user agent=] may note the reason in a user-friendly
Ok switched to should.

2025-06-16 19:54 UTC, npm1 commented on spec/index.bs
> +Given a |realm|, a {{DOMString}} |message|, and an {{IdentityCredentialErrorInit}} |options|, the
I'm told I should not use the constructor so used a create method instead

2025-06-16 19:55 UTC, npm1 commented on spec/index.bs
> +            [=global object/realm=].
Fixed I think. Side note: I think our implementation validates the endpoints at the beginning, not at this point in time. But this is unrelated to this PR so will fix later

2025-06-16 20:16 UTC, cbiesinger approved these changes

2025-06-16 20:16 UTC, cbiesinger commented on spec/index.bs
> +<xmp class="idl">
this does not seem resolved?

2025-06-16 20:16 UTC, cbiesinger commented on spec/index.bs
> -To <dfn>create an IdentityCredential</dfn> given a [=sequence=] of  {{IdentityProviderRequestOptions}}
Why are you removing the "sequence" part? Does that not break multi-IDP?

2025-06-16 20:38 UTC, npm1 commented on spec/index.bs
> -To <dfn>create an IdentityCredential</dfn> given a [=sequence=] of  {{IdentityProviderRequestOptions}}
Bad rebase...

2025-06-16 20:38 UTC, npm1 commented on spec/index.bs
> +        1. Otherwise, if {{IdentityAssertionResponse/token}} was specified, let |tokenString|
I mean a response is only received in case of a successful fetch. Not sure what you mean?

2025-06-16 20:39 UTC, npm1 commented on spec/index.bs
> +<xmp class="idl">
Sorry I had started a change and resolved but lost my progress midway. Done now

2025-06-16 22:05 UTC, cbiesinger commented on spec/index.bs
> +        1. Otherwise, if {{IdentityAssertionResponse/token}} was specified, let |tokenString|
don't you get a response also for 404? I guess I'm not certain how the fetch API handles that

2025-06-16 22:07 UTC, cbiesinger approved these changes

2025-06-16 22:07 UTC, cbiesinger commented on spec/index.bs
> +bool), where the bool indicates whether to throw the exception immediately.
As far as I can tell, the new text is identical to the old text except for line wrapping. But it should probably say that it can also return an IdentityCredentialError?

2025-06-17 14:41 UTC, npm1 commented on spec/index.bs
> +        1. Otherwise, if {{IdentityAssertionResponse/token}} was specified, let |tokenString|
`responseBody` will only be converted to JSON without throwing if it fetched. Added a step to make it clearer

2025-06-17 15:02 UTC, cbiesinger commented on spec/index.bs
> +        1. Otherwise, if {{IdentityAssertionResponse/token}} was specified, let |tokenString|
But 404 responses do have a response body.

Maybe more importantly, we do want to process "error" in 404 responses as well

2025-06-17 16:11 UTC, npm1 commented on spec/index.bs
> +        1. Otherwise, if {{IdentityAssertionResponse/token}} was specified, let |tokenString|
Ah yea. Hmm well it seems we DO allow http errors in our implementation, so we do parse the body in those cases, for ID assertion in particular. Fixed I think?

2025-06-17 16:12 UTC, cbiesinger commented on spec/index.bs
> +        1. Otherwise, if |response|'s [=response/status=] is an [=ok status=], set |credential| to
is this missing a "not"?

2025-06-17 16:15 UTC, npm1 commented on spec/index.bs
> +        1. Otherwise, if |response|'s [=response/status=] is an [=ok status=], set |credential| to
Oops yea

2025-06-17 16:17 UTC, cbiesinger approved these changes
lgtm. we should probably add status checks to our other fetches...

2025-06-17 16:19 UTC, npm1 commented
> lgtm. we should probably add status checks to our other fetches...

Sure, filed https://github.com/w3c-fedid/FedCM/issues/745

2025-06-17 17:53 UTC, yi-gu commented on spec/index.bs
> +        1. Otherwise, if |response|'s [=response/status=] is not an [=ok status=], set |credential|
In Chrome we may update the error even if the IdP didn't specify an `error` in the response. e.g. we try to map 500/503 to the enum values to give users more context: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/webid/idp_network_request_manager.cc;l=895?q=content%2Fbrowser%2Fwebid%2Fidp_network_request_manager.cc

2025-06-17 17:53 UTC, yi-gu commented on spec/index.bs
> +Only one of `token`, `continue_on`, and `error` should be specified.
I know it's specified in the algorithm above, but do you think it's worth calling out which will be respected if multiple are specified?

2025-06-17 21:31 UTC, yi-gu commented
Thanks! LGTM

2025-06-17 21:50 UTC, TallTed requested changes

2025-06-17 21:50 UTC, TallTed commented on spec/index.bs
> +                the [=response/status=] is 503.
```suggestion
            1. The user agent MAY set |credential|'s {{IdentityCredentialError/error}}
               based on |response|'s [=response/status=]. For example, if the
               [=response/status=] is `500`, it could be set to "server_error",
               and if the [=response/status=] is `503`, it could be set to
               "temporarily_unavailable".
```

2025-06-17 21:50 UTC, TallTed commented on spec/index.bs
> +Only one of `token`, `continue_on`, and `error` should be specified. When multiple are specified,
```suggestion
Only one of `token`, `continue_on`, or `error` should be specified. When multiple are specified,
```

2025-06-17 21:50 UTC, TallTed commented on spec/index.bs
> +the response.
```suggestion
the order of processing is [`error`, `token`, `continue_on`], so the first encountered
will be used in the response.
```

2025-06-24 15:34 UTC, bvandersloot-mozilla approved these changes

2025-06-24 15:53 UTC, merged

2025-06-24 16:06 UTC, hlflanagan commented
Discussed in [FedID CG/WG call, 24 June 2025](https://github.com/w3c-fedid/meetings/blob/main/2025/2025-06-24-FedCM-notes.md)