Refactor the Login status API out of the FedCM spec
w3c-fedid/FedCM pull request #642
Opened 2024-08-22 23:40 UTC by samuelgoto

Resolves #641.

2024-08-23 13:53 UTC, npm1 commented
Uhm is this a request from someone? Also I'm not sure but I imagine there needs to be some procedure to add a new spec to the WG (even if it is all extracted from the current spec). Finally, in terms of editor I would suggest to name the one who actually wrote this which I think is @cbiesinger

2024-08-23 16:33 UTC, cbiesinger commented
> Also I'm not sure but I imagine there needs to be some procedure to add a new spec to the WG (even if it is all extracted from the current spec).

As far as I know the primary requirement is that the spec is in the charter, which it is (https://www.w3.org/2024/03/wg-fedid-charter.html#deliverables)

I see this was also added to the agenda for the next call

2024-08-23 16:34 UTC, cbiesinger commented on spec/login-status.bs
> +spec: webdriver; urlPrefix: https://w3c.github.io/webdriver/
A lot of these spec references are not needed for login status

2024-08-23 16:36 UTC, cbiesinger commented on spec/login-status.bs
> +Editor: Christian Biesinger, w3cid 50308, Google Inc. https://google.com, cbiesinger@chromium.org
Apparently my w3cid is 39461

2024-08-23 16:43 UTC, samuelgoto commented
> Uhm is this a request from someone?

Yeah, we have always intended to break the Login Status spec out of the FedCM spec, but never got to it: a browser vendor should be able to implement the Login Status API without having to implement the FedCM API.

https://github.com/privacycg/is-logged-in/issues/55#issuecomment-1749419249
https://www.w3.org/2023/09/13-login-status-minutes.html
https://www.w3.org/2024/03/wg-fedid-charter.html#deliverables (separate and orthogonal deliverables)

and more recently:

https://github.com/w3c-fedid/FedCM/issues/640#issue-2481927370

> Also I'm not sure but I imagine there needs to be some procedure to add a new spec to the WG (even if it is all extracted from the current spec)

I'm already working with @hlflanagan and @wseltzer to figure out how to go about this.  We would likely want to also move the spec to its own repo and the login-status repo from the CG to the WG:

https://github.com/fedidcg/login-status

We also want to coordinate with @johnwilander if he would rather have us use the FedID CG repo or the Privacy CG repo as the basis for the FedID WG repo (e.g. keeping the history and the issues). Either works for me, but we can have that discussion separately.

> Finally, in terms of editor I would suggest to name the one who actually wrote this which I think is @cbiesinger

Yep, chatted with @cbiesinger who agreed to edit here too. Done.

We also want to coordinate with @johnwilander and @bvandersloot-mozilla if they still feel comfortable sharing co-editorship here (TPAC 2023 we had [the three of us as co-editors](https://github.com/fedidcg/login-status)).

2024-08-23 16:50 UTC, samuelgoto commented on spec/login-status.bs
> +Editor: Christian Biesinger, w3cid 50308, Google Inc. https://google.com, cbiesinger@chromium.org
ha, good catch, done.

2024-08-23 17:45 UTC, npm1 requested changes

2024-08-23 17:45 UTC, npm1 commented on spec/login-status.bs
> +spec:infra; type:dfn; text:list
Remove the unused.

2024-08-23 17:45 UTC, npm1 commented on spec/login-status.bs
> +<style>
I think we can remove this altogether?

2024-08-23 17:45 UTC, npm1 commented on spec/login-status.bs
> +<script src="https://fedidcg.github.io/FedCM/static/underscore-min.js"></script>
Remove?

2024-08-23 17:45 UTC, npm1 commented on spec/login-status.bs
> +Note: use the introduction from the explainer.
?

2024-08-23 17:45 UTC, npm1 commented on spec/login-status.bs
> +# The Login Status API # {#browser-api-login-status}
This does not make sense as a title anymore because this is the title of the spec.

2024-08-23 17:45 UTC, npm1 commented on spec/login-status.bs
> +## Login Status Map ## {#hdr-login-status-map}
Hence lower the `#` for all titles I think. Also the new 1`#` titles need the separators

2024-08-23 17:45 UTC, npm1 commented on spec/login-status.bs
> +    1. If |client| is not [=same-origin with its ancestors=], return.
You seem to have copy pasted an outdated version. We updated this to same-site...

2024-08-23 17:45 UTC, npm1 commented on spec/index.bs
> -### Infrastructure algorithm ### {#infra-algorithm}
Oh this is not a good title. We may want to rename it once we move it

2024-08-23 17:45 UTC, npm1 commented on spec/login-status.bs
> +<pre class="biblio">
Remove unneeded?

2024-08-23 17:45 UTC, npm1 commented on spec/login-status.bs
> +Note: write down the Acknowledgements section.
?

2024-08-23 17:45 UTC, npm1 commented on spec/Makefile
> +spec: index.html login-status.html
I imagine we will undo these changes if it moves to its own repo.

2024-09-03 18:14 UTC, samuelgoto commented on spec/login-status.bs
> +spec: webdriver; urlPrefix: https://w3c.github.io/webdriver/
done

2024-09-03 18:17 UTC, samuelgoto commented on spec/login-status.bs
> +spec:infra; type:dfn; text:list
done

2024-09-03 18:27 UTC, samuelgoto reviewed
Done

Also, added John Wilander as a co-editor.

2024-09-03 18:27 UTC, samuelgoto commented on spec/login-status.bs
> +    1. If |client| is not [=same-origin with its ancestors=], return.
Are you sure? This seems to be up to date with HEAD?

https://github.com/w3c-fedid/FedCM/blob/main/spec/index.bs#L400

2024-09-03 18:27 UTC, samuelgoto commented on spec/login-status.bs
> +Note: write down the Acknowledgements section.
Same todo as in the FedCM spec?

https://github.com/w3c-fedid/FedCM/blob/main/spec/index.bs#L2952

2024-09-03 18:27 UTC, samuelgoto commented on spec/login-status.bs
> +<pre class="biblio">
done

2024-09-03 18:27 UTC, samuelgoto commented on spec/login-status.bs
> +# The Login Status API # {#browser-api-login-status}
done

2024-09-03 18:27 UTC, samuelgoto commented on spec/login-status.bs
> +## Login Status Map ## {#hdr-login-status-map}
done

2024-09-03 18:27 UTC, samuelgoto commented on spec/Makefile
> +spec: index.html login-status.html
yep

2024-09-03 18:27 UTC, samuelgoto commented on spec/index.bs
> -### Infrastructure algorithm ### {#infra-algorithm}
Sure. Lets do that on a separate pass to keep the history.

2024-09-03 20:08 UTC, npm1 commented on spec/login-status.bs
> +    1. If |client| is not [=same-origin with its ancestors=], return.
That same same-site?

2024-09-03 20:49 UTC, samuelgoto commented on spec/login-status.bs
> +    1. If |client| is not [=same-origin with its ancestors=], return.
Ah, yes, interesting, for some reason I missed this PR in my branch:

https://github.com/w3c-fedid/FedCM/commit/548e7b2a5fc990c7588ed2c9af46416c0f00be07

I sync and merged and I think this is now up to date. Sanity check?

2024-09-04 16:49 UTC, npm1 commented on spec/login-status.bs
> +    1. If |client| is not [=same-origin with its ancestors=], return.
Now it seems fine. I guess the plan is to create a new repo for this, right? So anyways the change in this repo will only be to remove the existing spec text.

2024-09-04 17:19 UTC, samuelgoto commented on spec/login-status.bs
> +    1. If |client| is not [=same-origin with its ancestors=], return.
> . I guess the plan is to create a new repo for this, right? 

Yes

> So anyways the change in this repo will only be to remove the existing spec text.

Yes, that's correct. I wanted to move into a single PR so that it is clear that the break was clean, rather than in two separate PRs into different repos.

2024-09-05 15:54 UTC, npm1 approved these changes

2024-09-05 16:11 UTC, cbiesinger commented on spec/index.bs
> +                    [login-status.html#login-status-http](HTTP header) API during the login
I wonder if this should be a [==] reference... may need a <dfn export> in the login status spec

Also, don't we need a link to login-status in the anchors section at the top? As-is, there are a lot of failed links: https://github.com/w3c-fedid/FedCM/actions/runs/10690399462/job/29634680467#step:3:839

2024-09-05 16:11 UTC, cbiesinger commented on spec/login-status.bs
> +        text: same-origin with its ancestors; url: same-origin-with-its-ancestors</pre>
I don't think this is actually used?

2024-09-05 18:10 UTC, samuelgoto commented on spec/index.bs
> +                    [login-status.html#login-status-http](HTTP header) API during the login
ah, i think that did the trick! PTAL!?

https://github.com/w3c-fedid/FedCM/pull/642/commits/57509ce9497acdc7857cdeff4a20c9c3ffc8778f

2024-09-05 18:11 UTC, samuelgoto commented on spec/login-status.bs
> +        text: same-origin with its ancestors; url: same-origin-with-its-ancestors</pre>
I think that's still used here?

https://github.com/w3c-fedid/FedCM/blob/main/spec/index.bs#L840

2024-09-05 18:25 UTC, cbiesinger commented on spec/login-status.bs
> +        text: same-origin with its ancestors; url: same-origin-with-its-ancestors</pre>
Yes, but it's not used in the login status spec?

2024-09-05 18:26 UTC, cbiesinger approved these changes
lgtm modulo the same-origin comment

2024-09-05 18:28 UTC, samuelgoto commented on spec/login-status.bs
> +        text: same-origin with its ancestors; url: same-origin-with-its-ancestors</pre>
ah, right. done.

2024-09-05 18:32 UTC, merged