Add mode for FedCM
w3c-fedid/FedCM pull request #660
Opened 2024-10-02 19:35 UTC by tttzach

Fixes https://github.com/w3c-fedid/active-mode/issues/2

2024-10-02 20:35 UTC, samuelgoto commented on spec/index.bs
> +        1. [=Show an IDP login dialog=] with |config| and |provider|.
Don't you need to check somewhere if mode == "active" before calling [=Show an IDP login dialog=]?

2024-10-02 20:39 UTC, tttzach commented on spec/index.bs
> +        1. [=Show an IDP login dialog=] with |config| and |provider|.
I was hoping for this to just be a definition of the |showIdpLoginDialog| behavior, the check for mode == "active" comes in line 806.

2024-10-02 21:04 UTC, cbiesinger reviewed
Generally looks good. See comments below. We should probably add a Note: in some appropriate place that the user agent should consider displaying the account chooser in a louder way if mode is active.

2024-10-02 21:04 UTC, cbiesinger commented on spec/index.bs
> +        * Trigger |showIdpLoginDialog| directly. The user agent SHOULD set |loginStatus| to [=unknown=].
This needs to be written a bit differently. As written it will trigger the IDP login dialog twice (here and on line 806).

Either this line needs to be more informal ("Trigger an IDP login dialog by following these steps") or just describe directly what to do. Since we already allow returning failure above, this could just be something like:

```
* If |options|'s {{IdentityCredentialRequestOptions/mode}} is [=active=] and [=transient activation=] is present, trigger |showIdpLoginDialog|.
```

2024-10-03 14:26 UTC, TallTed requested changes
Minor, human-facing

2024-10-03 14:26 UTC, TallTed commented on spec/index.bs
>  The {{IdentityCredentialRequestOptions}} also contains a {{IdentityCredentialRequestOptionsContext}}
This goes along with the suggestion below.
```suggestion
The {{IdentityCredentialRequestOptions}} also contains an {{IdentityCredentialRequestOptionsContext}},
```

2024-10-03 14:26 UTC, TallTed commented on spec/index.bs
> +which the user agent can use to specify different behaviors or dialog types.
```suggestion
which the user agent can use to provide a more meaningful dialog to users,
and an {{IdentityCredentialRequestOptionsMode}},
which the user agent can use to specify different behaviors or dialog types.
```

2024-10-03 14:30 UTC, yi-gu commented on spec/index.bs
>      1. Let |loginStatus| be the result of [=get the login status=] with
I'm wondering if we should start the algorithm by checking the mode and user activation requirement. e.g. if there's no user activation when active mode is used, we don't need to update the login status. See https://github.com/yi-gu/FedCM/blob/main/explorations/static/FedCM_Mode_API.jpeg?raw=true

In addition, we should also mention an active mode must replace pending passive mode request unless people consider that as a UA specific choice.

2024-10-03 19:59 UTC, tttzach commented on spec/index.bs
> +        1. [=Show an IDP login dialog=] with |config| and |provider|.
This is now an algorithm, thanks!

2024-10-03 19:59 UTC, tttzach commented on spec/index.bs
> +    1. Let |showIdpLoginDialog| be an affordance to [=show an IDP login dialog=]:
This is now an algorithm, thanks!

2024-10-03 20:00 UTC, tttzach commented on spec/index.bs
>      1. If |loginStatus| is [=logged-out=], the user agent MUST do one of the following:
Fixed, thank you!

2024-10-03 20:01 UTC, tttzach commented on spec/index.bs
> +        * Trigger |showIdpLoginDialog| directly. The user agent SHOULD set |loginStatus| to [=unknown=].
I used your suggestion, thanks!

2024-10-03 20:01 UTC, tttzach commented on spec/index.bs
>  The {{IdentityCredentialRequestOptions}} also contains a {{IdentityCredentialRequestOptionsContext}}
Fixed, thanks!

2024-10-03 20:01 UTC, tttzach commented on spec/index.bs
> +which the user agent can use to specify different behaviors or dialog types.
Fixed, thanks!

2024-10-03 20:02 UTC, tttzach commented on spec/index.bs
>      1. Let |loginStatus| be the result of [=get the login status=] with
Good catch, I made it such that we check for the mode an user activation requirement prior to the login status, and also added a line to represent replacing the pending passive mode request, if any.

2024-10-03 20:17 UTC, tttzach commented on spec/index.bs
> +            * If the user continues, trigger |showIdpLoginDialog|.
Got it, thanks!

2024-10-04 16:34 UTC, TallTed requested changes
trivial, editorial

2024-10-04 16:34 UTC, TallTed commented on spec/index.bs
> +        1. If [=transient activation=] is present and if there is a pending
redundant if
```suggestion
        1. If [=transient activation=] is present and there is a pending
```

2024-10-07 18:14 UTC, tttzach commented on spec/index.bs
> +        1. If [=transient activation=] is present and if there is a pending
Thanks!

2024-10-07 19:13 UTC, cbiesinger approved these changes
Thanks, looks good modulo two minor comments

2024-10-07 19:13 UTC, cbiesinger commented on spec/index.bs
> +            request where |mode| is [=passive=], return (failure, true) for the
Hmm this needs to be written differently (the previous request is not (or may not be) at this point in the algorithm so you can't just return here from there.

Maybe something like, `cancel the previous request as if a {{CredentialRequestOptions/signal}} was given to it and was [=AbortSignal/aborted=]`?

2024-10-07 19:13 UTC, cbiesinger commented on spec/index.bs
> +        * If |mode| is [=active=] and [=transient activation=] is present,
I got a bit lost in the control flow but I think we verify earlier that transient activation is present if mode is active so we probably don't need that check here.

2024-10-08 14:55 UTC, tttzach commented on spec/index.bs
> +            request where |mode| is [=passive=], return (failure, true) for the
Used your suggestion, thanks!

2024-10-08 14:56 UTC, tttzach commented on spec/index.bs
> +        * If |mode| is [=active=] and [=transient activation=] is present,
Yes we do indeed verify earlier, removed the transient activation check. Thanks!

2024-10-08 16:51 UTC, TallTed commented on spec/index.bs
> +            was [=AbortSignal/aborted=].
```suggestion
            as if a {{CredentialRequestOptions/signal}} of
            [=AbortSignal/aborted=] was given to it.
```

2024-10-08 17:10 UTC, tttzach commented on spec/index.bs
> +            was [=AbortSignal/aborted=].
Thanks, Ted!

2024-10-15 15:21 UTC, wseltzer commented
Discussed in Oct. 15 call. [minutes to be linked]

2024-10-15 15:24 UTC, tttzach commented
@aaronpk @bvandersloot-mozilla @philsmart Please take a look!

2024-10-15 15:59 UTC, samuelgoto commented on spec/index.bs
> +        1. The user agent MAY use the
```suggestion
        1. The user agent SHOULD use the
```

Should we use stronger language here?

2024-10-15 15:59 UTC, samuelgoto commented on spec/index.bs
> +To <dfn>fetch the config file and show an IDP login dialog</dfn> given an {{IdentityProviderConfig}} |provider|, and a |globalObject|, run the following steps. This returns
Wouldn't it be possible to break this into two separate algorithms so that they are more reusable/narrow?

2024-10-15 16:00 UTC, samuelgoto commented on spec/index.bs
> +    1. If |config| is failure, return failure.
at this point, haven't we already fetched the config file?

2024-10-15 16:47 UTC, philsmart commented
From the perspective of at least the R&E federations I am involved with, 'active' mode is a better fit. This mode supports authentication with Identity Providers (IdPs) that the user has not yet logged into (as signalled by the login status API). 

Supporting multiple IdPs in 'active' mode would be helpful, but it could result in the same account fetching issues as enabling multi-IdP in 'passive' mode. The 'passive' mode addressed this (if I recall correctly) by including only the IdPs you've signed into, which brings us back to the same issue (unable to use an IdP you've not logged into). This can be addressed for now by using an external IdP discovery service and populating FedCM with a single IdP in 'active' mode.

For what it's worth, I agree with renaming 'button' and 'widget' to 'active' and 'passive', it is clearer.

2024-10-15 16:53 UTC, tttzach commented on spec/index.bs
> +    1. If |config| is failure, return failure.
Hmm this is the algorithm, unless you meant where we use this then no not yet - we haven't already fetched the config file upon checking the login status bit but it does come a couple lines after. Would it make sense to move the config file fetch to before checking the login status bit?

2024-10-15 16:53 UTC, tttzach commented on spec/index.bs
> +To <dfn>fetch the config file and show an IDP login dialog</dfn> given an {{IdentityProviderConfig}} |provider|, and a |globalObject|, run the following steps. This returns
Ah it looks like these two already exist separately. Removed and used them instead, thanks!

2024-10-15 16:53 UTC, tttzach commented on spec/index.bs
> +        1. The user agent MAY use the
Switched to stronger language here and similar text elsewhere, thanks!

2024-10-18 15:34 UTC, yi-gu approved these changes

2024-10-21 16:40 UTC, cbiesinger approved these changes

2024-10-21 17:28 UTC, npm1 requested changes

2024-10-21 17:28 UTC, npm1 commented on spec/index.bs
> +        1. If [=transient activation=] is not present, return (failure, true).
transient activation is a Window concept. You need to specify which Window needs to have it. Also `present` is not the right term here since this is a boolean. Maybe "If W has transient activation[...]"

2024-10-21 17:28 UTC, npm1 commented on spec/index.bs
> +        1. If [=transient activation=] is present and there is a pending
This part about pending request is also not precise enough. Presumably this is also scoped to something (perhaps top-level browsing context?). In addition, you are never going to reach this because we disallow this from credential management in 8.2 https://w3c.github.io/webappsec-credential-management/#algorithm-request so that will need to be modified as well at some point

2024-10-21 17:28 UTC, npm1 commented on spec/index.bs
> +            [=AbortSignal/aborted=] was given to it.
Hmm but isnt the abort signal only for the developer to use? This does not make sense to me, is this actually what we do?

2024-10-21 17:28 UTC, npm1 commented on spec/index.bs
> +    1. If |loginStatus| is [=logged-out=]
Missing : at the end

2024-10-21 17:28 UTC, npm1 commented on spec/index.bs
> +        1. If |mode| is [=passive=], the user agent MUST do one of the following:
You can use otherwise here (there are only two modes)

2024-10-21 17:28 UTC, npm1 commented on spec/index.bs
> +            [=fetch the config file=] and [=show an IDP login dialog=].
Algorithms usually have inputs and outputs

2024-10-21 17:28 UTC, npm1 commented on spec/index.bs
> +                    [=fetch the config file=] and [=show an IDP login dialog=].
This used to be accurately specified, the simplification is not right

2024-10-21 17:28 UTC, npm1 commented on spec/index.bs
> +        1. The user agent SHOULD use the
Why change may to should?

2024-10-21 17:28 UTC, npm1 commented on spec/index.bs
> +            in via |account|, and set the result in |permission|. The user agent SHOULD use |options|'s
Why change may to should?

2024-10-21 17:28 UTC, npm1 commented on spec/index.bs
> +            [=fetch the config file=] and [=show an IDP login dialog=].
Needs to handle failure case similar to how it was being done below

2024-10-22 15:38 UTC, bvandersloot-mozilla commented on spec/index.bs
> +            in via |account|, and set the result in |permission|. The user agent SHOULD use |options|'s
ditto.

2024-10-22 15:39 UTC, bvandersloot-mozilla commented on spec/index.bs
> +        1. The user agent SHOULD use the
ditto

2024-10-22 15:43 UTC, bvandersloot-mozilla requested changes
why SHOULD?

2024-10-23 16:29 UTC, tttzach reviewed
Thanks for the review, please take another look!

2024-10-23 16:29 UTC, tttzach commented on spec/index.bs
> +        1. The user agent SHOULD use the
Reverted, thanks!

2024-10-23 16:29 UTC, tttzach commented on spec/index.bs
> +            in via |account|, and set the result in |permission|. The user agent SHOULD use |options|'s
Reverted, thanks!

2024-10-23 16:29 UTC, tttzach commented on spec/index.bs
> +                    [=fetch the config file=] and [=show an IDP login dialog=].
Went with what we had in the original spec, thanks!

2024-10-23 16:29 UTC, tttzach commented on spec/index.bs
> +        1. If |mode| is [=passive=], the user agent MUST do one of the following:
Done, thanks!

2024-10-23 16:29 UTC, tttzach commented on spec/index.bs
> +            [=fetch the config file=] and [=show an IDP login dialog=].
Went with what we had in the original spec, thanks!

2024-10-23 16:29 UTC, tttzach commented on spec/index.bs
> +            [=fetch the config file=] and [=show an IDP login dialog=].
Went with what we had in the original spec, thanks!

2024-10-23 16:29 UTC, tttzach commented on spec/index.bs
> +    1. If |loginStatus| is [=logged-out=]
Done, thanks!

2024-10-23 16:29 UTC, tttzach commented on spec/index.bs
> +            [=AbortSignal/aborted=] was given to it.
No we don't actually use the abort signal for this case, but instead we directly reject the previous request. Though this was why its worded this way: https://github.com/w3c-fedid/FedCM/pull/660#discussion_r1790743904

Maybe we can get rid of `as if a {{CredentialRequestOptions/signal}} of [=AbortSignal/aborted=] was given to it.`?

2024-10-23 16:29 UTC, tttzach commented on spec/index.bs
> +        1. If [=transient activation=] is present and there is a pending
Good catch on the scoping... let me know if |W|'s top-level browsing context works or if that should be even more specific. Should modifying 8.2 be in this PR?

2024-10-23 16:29 UTC, tttzach commented on spec/index.bs
> +        1. If [=transient activation=] is not present, return (failure, true).
Used your suggestion, thanks!

2024-10-31 02:35 UTC, tttzach commented on spec/index.bs
> +    1. Let |globalObject| be the [=current global object=].
Fixed, thanks!

2024-10-31 02:36 UTC, tttzach commented on spec/index.bs
> +                    1. Let |config| be the result of running [=fetch the config file=]
Hmm Sam prefers them to be separate: https://github.com/w3c-fedid/FedCM/pull/660#discussion_r1801495711 but I do like the helper function so I brought it back.

2024-10-31 02:36 UTC, tttzach commented on spec/index.bs
> +            context where |mode| is [=passive=], reject the previous request.
Added, thanks!

2024-10-31 02:36 UTC, tttzach commented on spec/index.bs
> +        1. Otherwise, and if there is a pending request on |W|'s top-level browsing
Added a link and rephrased it a little, let me know if this works!

2024-10-31 02:36 UTC, tttzach commented on spec/index.bs
> +    1. Let |W| be |globalObject|'s [=associated Window=].
Fixed, thanks!

2024-10-31 18:25 UTC, npm1 commented on spec/index.bs
> +            [top-level browsing context](https://html.spec.whatwg.org/#bc-traversable) or on any
```suggestion
            [=Window/navigable=]'s [=navigable/top-level traversable=] or on any of its descendants
```
Added suggestion though did not check if the syntax is right but you get the idea

2024-10-31 18:25 UTC, npm1 commented on spec/index.bs
> +steps. This returns success or failure.
The return value is not being used in the callers, should they?

2024-10-31 18:26 UTC, npm1 commented on spec/index.bs
> +        1. If |mode| is [=active=], [=fetch the config file and show an IDP login dialog=]
You need to return failure if this fails.

2024-10-31 18:26 UTC, npm1 commented on spec/index.bs
> +                * If the user triggers this affordance, [=fetch the config file and show an IDP login dialog=]
You need to return failure if this fails.

2024-10-31 22:01 UTC, tttzach commented on spec/index.bs
> +            [top-level browsing context](https://html.spec.whatwg.org/#bc-traversable) or on any
Used your suggestion, thanks!

2024-10-31 22:01 UTC, tttzach commented on spec/index.bs
> +steps. This returns success or failure.
Fixed, thanks!

2024-10-31 22:01 UTC, tttzach commented on spec/index.bs
> +        1. If |mode| is [=active=], [=fetch the config file and show an IDP login dialog=]
Fixed, thanks!

2024-10-31 22:01 UTC, tttzach commented on spec/index.bs
> +                * If the user triggers this affordance, [=fetch the config file and show an IDP login dialog=]
Fixed, thanks!

2024-11-01 17:59 UTC, tttzach commented on spec/index.bs
> +            1. If |result| is failure, return (failure, false).
This should be true. Thanks!

2024-11-01 17:59 UTC, tttzach commented on spec/index.bs
> +                    1. If |result| is failure, return (failure, false).
Fixed, thanks!

2024-11-05 20:57 UTC, tttzach commented
@bvandersloot-mozilla Friendly ping :)

2024-11-14 19:20 UTC, hlflanagan commented
Note: discussed during https://github.com/fedidcg/meetings/blob/main/2024/2024-11-12-notes.md ; PR blocked pending @bvandersloot-mozilla review.

2024-11-18 13:38 UTC, bvandersloot-mozilla approved these changes

2024-11-18 17:01 UTC, merged