Specify the params API
w3c-fedid/FedCM pull request #661
Opened 2024-10-02 21:33 UTC by cbiesinger

Bug: w3c-fedid/custom-requests#2

2024-10-02 22:06 UTC, samuelgoto approved these changes

2024-10-03 14:20 UTC, TallTed requested changes
Minor, human-facing

2024-10-03 14:20 UTC, TallTed commented on spec/index.bs
> +        1. Let |json| be the result of [=serializing a javascript value to a json string=]
```suggestion
        1. Let |json| be the result of [=serializing a JavaScript value to a JSON string=]
```

2024-10-07 12:11 UTC, bvandersloot-mozilla commented on spec/index.bs
> +  record<USVString, any> params;
Is there a better option than `any` here? Would a single level do?

2024-10-07 16:09 UTC, cbiesinger commented on spec/index.bs
> +  record<USVString, any> params;
Perhaps I misunderstood your comment at https://github.com/w3c-fedid/custom-requests/issues/2#issuecomment-2342125876. But the reason I picked any was that people in that issue, especially @aaronpk, wanted arbitrary objects.

2024-10-07 17:09 UTC, samuelgoto commented on spec/index.bs
> +  record<USVString, any> params;
Yeah, I think we are better off with arbitrary (JSON-serializable) objects.

2024-10-07 17:10 UTC, samuelgoto commented on spec/index.bs
> +  record<USVString, any> params;
But, wouldn't `object` do @cbiesinger ?

2024-10-07 17:39 UTC, bvandersloot-mozilla commented on spec/index.bs
> +  record<USVString, any> params;
I think, if it is clear we are going to serialize it, it is probably fine. I forgot that conversation where Aaron was clear arbitrary structure was desired.

> But, wouldn't object do 
No because that would exclude a lot, e.g. `params: "a string"`

2024-10-07 18:06 UTC, samuelgoto commented on spec/index.bs
> +  record<USVString, any> params;
On a related note, I was hoping for the following:

```suggestion
  object params;
```

I was thinking that we would take directly an `object`, rather than a `record<USVString, any>`.

2024-10-07 18:09 UTC, samuelgoto commented on spec/index.bs
> +  record<USVString, any> params;
`params: "a string"` seems like a reasonable use case. so maybe it should be an union type?

```suggestion
  USVString or object params;
```

It doesn't seem to be that it is necessary to support:

- Arrays like `params: ["foo", {bar: 1}]`
- Booleans like `params: true`
- Numbers like `params: 3` or `params: 2.1` 
- Functions like `params: () => { return 1; }`

So, would `USVString or object` do?

2024-10-07 18:21 UTC, cbiesinger commented on spec/index.bs
> +  record<USVString, any> params;
(I don't think "any" matches a function type, I don't see that in https://webidl.spec.whatwg.org/#idl-any)

As per https://webidl.spec.whatwg.org/#idl-object I *think* `object` is separate from `record`?

But I don't feel strongly about any of this. Should we discuss on the call tomorrow?

2024-10-07 18:22 UTC, cbiesinger commented on spec/index.bs
> +  record<USVString, any> params;
@aaronpk any thoughts on whether we should allow non-maps for `params`?

2024-10-07 18:25 UTC, samuelgoto commented on spec/index.bs
> +  record<USVString, any> params;
I think that if we leave the semantics of the `params` to be `any` and functionally equivalent to `encodeURIComponent(JSON.stringify(param))` it will do what we want it to do:

```javascript
encodeURIComponent(JSON.stringify("foobar"))
// '%22foobar%22'

encodeURIComponent(JSON.stringify({foo: 1}))
// '%7B%22foo%22%3A1%7D'

encodeURIComponent(JSON.stringify([1, 2, 3]))
// '%5B1%2C2%2C3%5D'
```

2024-10-08 15:16 UTC, bvandersloot-mozilla approved these changes

2024-10-08 15:17 UTC, bvandersloot-mozilla commented on spec/index.bs
> +  record<USVString, any> params;
`any` is also appropriate, and probably better

2024-10-08 15:31 UTC, elf-pavlik approved these changes

2024-10-08 15:33 UTC, wseltzer commented
Discussed at 8 October meeting [minutes to be linked]. Agreed to merge when reviews complete.

2024-10-08 15:33 UTC, cbiesinger commented on spec/index.bs
> +  record<USVString, any> params;
Changed to any

2024-10-08 15:49 UTC, cbiesinger commented on spec/index.bs
> +  record<USVString, any> params;
Changed to any now.

2024-10-08 16:30 UTC, samuelgoto approved these changes
LGTM++

2024-10-08 16:32 UTC, samuelgoto commented on spec/index.bs
> +        1. Let |json| be the result of [=serializing a javascript value to a json string=]
I think this is a reference to an algorithm, so we have to keep the casing (i believe @cbiesinger ?).

2024-10-08 16:33 UTC, samuelgoto commented
> Discussed at 8 October meeting [minutes to be linked]. Agreed to merge when reviews complete.

I think we got all reviews complete. Can I merge this? Or is there anything else actionable here?

2024-10-08 16:35 UTC, cbiesinger commented on spec/index.bs
> +        1. Let |json| be the result of [=serializing a javascript value to a json string=]
No, bikeshed is smart.

2024-10-08 16:36 UTC, samuelgoto commented on spec/index.bs
> +        1. Let |json| be the result of [=serializing a javascript value to a json string=]
ah, thanks for the clarification!! lgtm++.

2024-10-08 17:52 UTC, samuelgoto commented
> Can I merge this? Or is there anything else actionable here?

I got the ack from @wseltzer to merge. Done.

2024-10-08 17:52 UTC, merged

2024-10-14 23:22 UTC, samuelgoto commented on spec/index.bs
> +        1. Let |json| be the result of [=serializing a JavaScript value to a JSON string=]
@cbiesinger something that was brought to my attention while reviewing a different PR was that this algorithm [can throw](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#exceptions): that's unlikely and seems like a programming error, but seemed worth noting somewhere here what we should do when this throws.