Specify multiple configURLs
w3c-fedid/FedCM pull request #667
Opened 2024-10-28 19:57 UTC by cbiesinger

Bug: #552

2024-10-28 20:29 UTC, TallTed requested changes
All to increase clarity.

2024-10-28 20:29 UTC, TallTed commented on spec/index.bs
> +    1. Let |config|, |discovery|, |accounts_url| and |login_url| be null.
```suggestion
    1. Let |config|, |discovery|, |accounts_url|, and |login_url| be null.
```

2024-10-28 20:29 UTC, TallTed commented on spec/index.bs
> +        set to the following steps given a <a spec=fetch for=/>response</a> |response| and |responseBody|:
```suggestion
        set to the following steps, given a <a spec=fetch for=/>response</a> |response| and |responseBody|:
```

2024-10-28 20:29 UTC, TallTed commented on spec/index.bs
> +        {{IdentityProviderWellKnown/login_url}} are set:
```suggestion
    1. If |discovery|.{{IdentityProviderWellKnown/accounts_endpoint}} and 
        |discovery|.{{IdentityProviderWellKnown/login_url}} are set:
```

2024-10-28 20:29 UTC, TallTed commented on spec/index.bs
> +            |provider|, |discovery|.{{IdentityProviderWellKnown/accounts_endpoint}}
```suggestion
            |provider|, |discovery|.{{IdentityProviderWellKnown/accounts_endpoint}},
```

2024-10-28 20:29 UTC, TallTed commented on spec/index.bs
> +            |config|.{{IdentityProviderAPIConfig/accounts_endpoint}} and |globalObject|.
```suggestion
            |config|.{{IdentityProviderAPIConfig/accounts_endpoint}}, and |globalObject|.
```

2024-10-28 20:29 UTC, TallTed commented on spec/index.bs
> +            |config|.{{IdentityProviderAPIConfig/login_url}} and |globalObject|.
```suggestion
            |config|.{{IdentityProviderAPIConfig/login_url}}, and |globalObject|.
```

2024-10-28 20:29 UTC, TallTed commented on spec/index.bs
> +            |discovery|.{{IdentityProviderWellKnown/login_url}} and |globalObject|.
```suggestion
            |discovery|.{{IdentityProviderWellKnown/login_url}}, and |globalObject|.
```

2024-10-28 20:29 UTC, TallTed commented on spec/index.bs
> +            |discovery|.{{IdentityProviderWellKnown/provider_urls}}[0] and |globalObject|.
```suggestion
            |discovery|.{{IdentityProviderWellKnown/provider_urls}}[0], and |globalObject|.
```

2024-10-29 16:07 UTC, cbiesinger commented
Thanks @TallTed, done. (Some of the lines you commented on aren't new, I just changed the indentation)

2024-10-29 17:58 UTC, npm1 commented on spec/index.bs
> +        1. Set |discovery| to the result of [=converted to an IDL value|converting=] |json|
Why are we calling this `discovery`?

2024-10-29 17:58 UTC, npm1 commented on spec/index.bs
> +    1. If |rpOrigin| is not an [=opaque origin=], and |rootUrl|'s [=url/host=] is equal
This seems to mean that the well known file needs to be present now in this case (otherwise it will fail in the previous line), whereas before it could pass? Is this change intentional? Why can't we keep the existing behavior where we just do not fetch the well-known in this case?

2024-10-29 17:58 UTC, npm1 commented on spec/index.bs
> +        1. If |login_url| or |accounts_url| is failure, return failure.
Ah maybe an existing issue but I don't know if this is allowed to return on behalf of the algorithm since these steps are done in processResponseConsumeBody which is an algorithm of its own. So maybe modify variables as opposed to return failure?

2024-10-30 21:04 UTC, cbiesinger reviewed
Please take another look!

2024-10-31 17:53 UTC, npm1 commented on spec/index.bs
> +        1. Set |discovery| to the result of [=converted to an IDL value|converting=] |json|
Well we call the other one `config`, perhaps we can call this one `wellKnown`?

2024-10-31 17:54 UTC, npm1 approved these changes

2024-10-31 17:58 UTC, cbiesinger commented on spec/index.bs
> +        1. Set |discovery| to the result of [=converted to an IDL value|converting=] |json|
Done.

2024-11-26 16:42 UTC, npm1 commented
Merging based on the WG discussion.

2024-11-26 16:42 UTC, merged