Specify the fields API
w3c-fedid/FedCM pull request #668
Opened 2024-10-28 21:30 UTC by cbiesinger

Bug: w3c-fedid/custom-requests#4

2024-10-28 22:30 UTC, TallTed requested changes

2024-10-28 22:30 UTC, TallTed commented on spec/index.bs
> +            with a "," between elements.
```suggestion
            with a comma ("`,`") between elements.
```

2024-10-28 22:30 UTC, TallTed commented on spec/index.bs
> +        1. Let |serializedFields| be the entries of |fields| concatenated with a ","
```suggestion
        1. Let |serializedFields| be the entries of |fields| concatenated with a comma ("`,`")
```

2024-10-28 22:30 UTC, TallTed commented on spec/index.bs
> +                is defined and the |provider|'s {{IdentityProviderConfig/clientId}} is not in the list of
```suggestion
                is defined, and the |provider|'s {{IdentityProviderConfig/clientId}} is not in the list of
```

2024-10-28 22:30 UTC, TallTed commented on spec/index.bs
> +                interpreting the strings as follows (this is the <dfn>list of recognized fields</dfn>):
```suggestion
                interpreting the strings in the <dfn>list of recognized fields</dfn> as follow:
```

2024-10-29 16:00 UTC, cbiesinger commented
Thanks @TallTed, addresssed your comments.

2024-10-29 17:39 UTC, npm1 commented on spec/index.bs
> +    1. Let |permission|, |permissionRequested|, and |isAutoSelected| be set to false.
Why do you like this new name better? This variable is true when the PP/TOS text is shown to the user. The user may still select an account, and I think that sort of counts as providing permission, so I find this new wording a bit confusing.

2024-10-29 17:39 UTC, npm1 commented on spec/index.bs
> +        1. Let |serializedFields| be the entries of |fields| concatenated with a comma ("`,`")
Hmm is this commonly called serialized, or perhaps rename this one?

2024-10-29 17:39 UTC, npm1 commented on spec/index.bs
> +    1. If |disclosureShownFor| contains all of "name", "email", and "picture", append
Is it actually the case that we only show disclosure text if all of these are present? My intuition was that it would be shown if at least one of these is present.

2024-10-29 17:39 UTC, npm1 commented on spec/index.bs
> +    1. Let |fields| be |provider|.{{IdentityProviderRequestOptions/fields}} or, if not specified,
s/specified/present. Alternatively, I think we could use = ['name', 'email', 'picture'] in the IDL

2024-11-07 21:10 UTC, cbiesinger commented on spec/index.bs
> +    1. Let |fields| be |provider|.{{IdentityProviderRequestOptions/fields}} or, if not specified,
Is that allowed by WebIDL? (it does not seem to be allowed by Chrome's IDL parser)

2024-11-07 21:10 UTC, cbiesinger commented on spec/index.bs
> +        1. Let |serializedFields| be the entries of |fields| concatenated with a comma ("`,`")
Renamed.

2024-11-07 21:10 UTC, cbiesinger commented on spec/index.bs
> +            [=compute the connection status/connected=], or if |provider|.
Done.

2024-11-07 21:10 UTC, cbiesinger commented on spec/index.bs
> +    1. Let |permission|, |permissionRequested|, and |isAutoSelected| be set to false.
We set permissionRequested to true when we call the [=request permission to sign-up=] algorithm, and that algorithm might not show a disclosure text (sign-up case when the user is signed in to only one account). Hence, the new name fits better.

2024-11-07 21:25 UTC, cbiesinger commented on spec/index.bs
> +    1. Let |fields| be |provider|.{{IdentityProviderRequestOptions/fields}} or, if not specified,
I'm told WebIDL does not allow such a default (only allows an empty list)

2024-11-07 21:28 UTC, npm1 approved these changes

2024-11-08 19:53 UTC, TallTed requested changes

2024-11-08 19:53 UTC, TallTed commented on spec/index.bs
>          1. If [=compute the connection status=] of |account|, |provider| and |globalObject| is
```suggestion
        1. If [=compute the connection status=] of |account|, |provider|, and |globalObject| is
```

2024-11-08 19:53 UTC, TallTed commented on spec/index.bs
> +            and |globalObject| and set |permission| to |true|.
```suggestion
            and |globalObject|, and set |permission| to |true|.
```

2024-11-08 19:53 UTC, TallTed commented on spec/index.bs
> +            if shown, always included name, email and picture. Newer identity providers should
```suggestion
            if shown, always included name, email, and picture. Newer identity providers should
```

2024-11-08 19:53 UTC, TallTed commented on spec/index.bs
> +            check `disclosure_shown_for` instead.
```suggestion
            instead check `disclosure_shown_for`.
```

2024-11-19 16:26 UTC, wseltzer commented
Discussed in 19 Nov 2024 WG call [link to minutes]. Not yet resolved.

2024-11-19 21:03 UTC, cbiesinger commented
I addressed TallTed's comments.

2024-11-19 21:43 UTC, TallTed approved these changes

2024-12-04 22:36 UTC, cbiesinger commented
I have updated the PR to make it optional for a user agent to show a disclosure text/permission prompt.

2024-12-04 22:50 UTC, npm1 commented on spec/index.bs
> +        1. The user agent SHOULD <dfn>support showing a permission prompt</dfn> as follows.
This is not a step. Can you merge it into the previous bullet with Additionally? If the user agent <dfn> supports...</dfn>, run the following:

2024-12-04 22:50 UTC, npm1 commented on spec/index.bs
> +        1. If |fields| is not [=list/empty=] and the user agent [=supports showing a permission prompt=]:
And with the previous change, this change is not needed.

2024-12-05 19:32 UTC, cbiesinger commented on spec/index.bs
> +        1. The user agent SHOULD <dfn>support showing a permission prompt</dfn> as follows.
Done.

2024-12-05 19:32 UTC, cbiesinger commented on spec/index.bs
> +        1. If |fields| is not [=list/empty=] and the user agent [=supports showing a permission prompt=]:
Done.

2024-12-05 19:36 UTC, cbiesinger commented
I've now also added a note that IDPs should support continue_on.

2024-12-05 20:23 UTC, npm1 reviewed
The last bullet point about context/mode seems unrelated to fields, should it go with the rest or totally outside of the new dfn?

2024-12-05 20:23 UTC, npm1 commented on spec/index.bs
> +            does not contain the fields required by the IDP. This is to support user agents that
nit: support galore, use synonym sometimes?

2024-12-06 18:25 UTC, TallTed commented on spec/index.bs
> +            does not contain the fields required by the IDP. This is to support user agents that
```suggestion
            does not contain the fields required by the IDP. This is to enable user agents that
```

2025-01-07 16:51 UTC, cbiesinger commented
Because this came up in the meeting -- if a user agent does not (want to) support this feature, then it would not "support[] showing a permission prompt" and would not fall into the "MUST" cases for the UI. That was at least the intention, if I missed a case please do point it out!

2025-01-07 16:55 UTC, bvandersloot-mozilla commented on spec/index.bs
> +            1. The user agent MUST prompt the user for permission to share the data in |fields|,
Does this force the display of a dialog with these fields shown?

2025-01-07 17:01 UTC, cbiesinger commented on spec/index.bs
> +            1. The user agent MUST prompt the user for permission to share the data in |fields|,
No because line 1380 makes this step only apply if the user agent supports showing a permission prompt.

2025-01-07 17:04 UTC, bvandersloot-mozilla commented on spec/index.bs
> +            1. The user agent MUST prompt the user for permission to share the data in |fields|,
Ah I missed that because tabs are hard and that line was broken up in the diff. 👍

2025-01-07 17:06 UTC, cbiesinger commented on spec/index.bs
> +            1. The user agent MUST prompt the user for permission to share the data in |fields|,
The autogenerated "Diff" link (in the initial comment in the PR) may be helpful for cases like this

2025-01-07 18:02 UTC, philsmart commented
I realise 'fields' are meaningful parts of data structures, but the naming seems less obvious to an IdP. They sound more specifically like 'requested (identity) attributes/claims'. Would it be worth looking at the naming of this, at least when it is POSTed to the assertions endpoint.

I guess overlapping with OIDCs use of Scopes, and SAML's use of RequestedAttributes.

2025-01-08 19:06 UTC, samuelgoto commented
> I realise 'fields' are meaningful parts of data structures, but the naming seems less obvious to an IdP. They sound more specifically like 'requested (identity) attributes/claims'. Would it be worth looking at the naming of this, at least when it is POSTed to the assertions endpoint.
> 
> I guess overlapping with OIDCs use of Scopes, and SAML's use of RequestedAttributes.

I think the closest to `fields` is OIDC's `claims`, rather than OAuth's `scope`. We picked `fields` because we figured it would be worth making it (a) OIDC-agnostic (e.g. it has to make sense for SAML too) and (b) align with the HTML spec, where `<forms>` have `<fieldset>` and `fields`. I do expect `fields` to connect to HTML's autofill at some point, so that's why I still think it is properly named. Happy to hear other suggestions, but just wanted to give some context of the considerations we made when picking it.

2025-01-09 10:44 UTC, philsmart commented
Thanks, @samuelgoto. That's a good point about being protocol agnostic. From an identity perspective, my understanding is that the RP will request certain attributes, and those are returned as verified (by the IdP) claims or assertions. 

I guess this pops up across the Identity and Access landscape in different guidelines and specifications e.g. [LDAP](https://datatracker.ietf.org/doc/html/rfc7643#section-4.1), [SAML](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf), SCIM, [OIDC](https://openid.net/specs/openid-connect-core-1_0.html#Terminology), [NIST SP800-63](https://pages.nist.gov/800-63-4/sp800-63.html)('Access to the service requires a defined list of attributes'), [NIST SP800-63c](https://pages.nist.gov/800-63-4/sp800-63c.html#common)('The federation transaction can also provide the RP with a set of identity attributes'), and so on. I personally wouldn't oppose reusing an existing term here, but I am not very familiar with alignment to the HTML specification, so maybe 'fields' is best.

2025-01-09 18:19 UTC, bvandersloot-mozilla approved these changes
Since this is not required, looks fine to me!

2025-01-09 18:38 UTC, merged

2026-09-20 22:57 UTC, ThisIsMissEm commented
@wseltzer @hlflanagan was this pull request reverted? I don't see this in the current editors draft: https://w3c-fedid.github.io/FedCM/ — there's just a bunch of `ISSUE: extension` blocks in the current draft.

Has Fields API shipped or not? The [status list](https://github.com/w3c-fedid/FedCM/wiki/Status-of-FPWD%E2%80%90identified-Issues-(Consensus-Blockers-for-CR)) says Fields APi is "now merged as part of FedCM"

2026-09-21 14:39 UTC, cbiesinger commented
The API has shipped in Chrome. And I see the changes from this PR in https://w3c-fedid.github.io/FedCM/#dom-identityproviderrequestoptions-fields and other places?

2026-09-21 16:33 UTC, ThisIsMissEm commented
@cbiesinger yeah, but the ID Assertion algorithm is missing them in the returned credential: https://w3c-fedid.github.io/FedCM/#fetch-an-identity-assertion

so you can request fields, but you never get them back?

2026-09-21 16:39 UTC, cbiesinger commented
We don't specify the format of the token. It's up to the IDP to include the value for the requested fields in whichever token format they use.

Are you suggesting that we could include the value of the fields from the accounts endpoint in the credential object? that would be possible, but is not what we were originally thinking. I would suggest filing a new issue for that use case.

2026-09-21 18:40 UTC, ThisIsMissEm commented
@cbiesinger I was expecting the `credentials` object to contain a top-level `fields` property, whether that's populated from the accounts endpoint or the "`Convert` json to an `IdentityAssertionResponse`" is unknown to me, but I suspect it may have to be the ID Assertion endpoint, since the IdP may need to enforce client permissions around retrieving certain fields, e.g,. needing `scope` of `account:email` in order to read the account's email (such that it shows in a consent flow)