Specify account labels
w3c-fedid/FedCM pull request #669
Opened 2024-10-29 18:25 UTC by cbiesinger

Bug: #553

2024-10-30 19:43 UTC, cbiesinger commented on spec/index.bs
> +dictionary IdentityProviderLabelConfig {
"exclude" is the obvious one. Conceivably we could also allow specifying multiple labels (could require all of them to match or just one)

2024-10-30 19:43 UTC, cbiesinger commented on spec/index.bs
> +            {{IdentityProviderAccount/labels}} does not [=list/contain=]
I mean, this is what we settled on in the explainer. I don't recall why we made this choice specifically, though. @samuelgoto do you remember?

2024-11-07 21:42 UTC, npm1 approved these changes
lgtm modulo naming

2024-11-26 16:45 UTC, hlflanagan commented
Discussed on https://github.com/fedidcg/meetings/blob/main/2024/2024-11-26-notes.md. Needs further review.

2024-12-04 21:45 UTC, cbiesinger commented
I would like to reiterate why we think this proposal is better than expanding login_hint/domain_hint to cover this.

Conceptually, we envision this as an IDP-internal selector that the RP need not/should not be aware of. Hence the design of putting it in the config URL to filter accounts from the account endpoint, both of which are under control of the IDP.

Putting this under control of the RP makes it easy to make programming errors -- forgetting to specify an account label leads to a UI with accounts that will not work, which is not a great user experience. Keeping this under control of the config file avoids that.

I realize that I did not do a good job framing this well in the meeting, sorry about that. I hope this helps in addition to the "alternatives considered" in #553.

2025-02-11 16:56 UTC, hlflanagan commented
Discussed again on 11 February 2025 call. Discussion: Agree in principle, may need a bit of bikeshedding.

2025-03-06 15:58 UTC, cbiesinger commented
On behalf of Chrome, we are happy to rename this.

Straw proposal:
- in the accounts endpoint: `labels` (like in the existing proposal)
- in the config file: `account_label`

Open to other suggestions!

2025-03-11 15:48 UTC, bvandersloot-mozilla requested changes

2025-03-11 15:48 UTC, bvandersloot-mozilla commented on spec/index.bs
> +  sequence<DOMString> labels;
how would `label_hints` work?

2025-03-11 15:48 UTC, bvandersloot-mozilla commented on spec/index.bs
> +  IdentityProviderLabelConfig accounts;
I'd rather this be `USVString account_label;`

2025-03-12 21:24 UTC, cbiesinger commented
I have updated the PR with the new names. I believe this is ready to merge now, unless @bvandersloot-mozilla wants to take another look?

2025-03-13 13:03 UTC, bvandersloot-mozilla approved these changes

2025-03-13 14:52 UTC, npm1 commented on spec/index.bs
> +        1. If |acc|["{{IdentityProviderAccount/picture}}"] is present, [=fetch the account picture=]
Why are you fetching the pictures again?

2025-03-13 18:14 UTC, cbiesinger commented on spec/index.bs
> +        1. If |acc|["{{IdentityProviderAccount/picture}}"] is present, [=fetch the account picture=]
ah that was a bad merge, fixed.

2025-03-13 18:27 UTC, npm1 approved these changes

2025-03-13 18:28 UTC, merged

2025-03-14 16:05 UTC, wseltzer commented
Discussed in [11 March meeting](https://github.com/fedidcg/meetings/blob/main/2025/2025-03-11-notes.md).