Specify "Use another account".
w3c-fedid/FedCM pull request #678
Opened 2024-11-04 22:05 UTC by cbiesinger

This depends on PR #660 (Mode API).

Bug: w3c-fedid/active-mode#3

2024-11-05 15:27 UTC, TallTed commented on spec/index.bs
> +To <dfn>select an account</dfn> given an |accountsList|, {{IdentityProviderModeSettings}}
```suggestion
To <dfn>select an account</dfn> given an |accountsList|, some {{IdentityProviderModeSettings}}
```

2024-11-05 15:28 UTC, TallTed commented on spec/index.bs
> +        1. If that returned sucess, go back to the [=fetch accounts step=].
```suggestion
        1. If that returned success, go back to the [=fetch accounts step=].
```

2024-11-05 15:41 UTC, npm1 requested changes
In the case the user is signed in to just one account, it does not appear to show the use other account feature. So the logic needs to change to account for that

2024-11-07 20:30 UTC, cbiesinger commented on spec/index.bs
> +        {{IdentityProviderModes/active}} if |options|.{{IdentityCredentialRequestOptions/mode}}
This will only be linked once PR #660 (mode API) lands. I don't know how to do PRs that depend on one another.

2024-11-07 20:30 UTC, cbiesinger commented
> In the case the user is signed in to just one account, it does not appear to show the use other account feature. So the logic needs to change to account for that

I updated the PR to add the additional logic where required, PTAL

2024-11-07 21:03 UTC, npm1 commented on spec/index.bs
> +        1. If that returned success, go back to the [=fetch accounts step=].
Otherwise return failure here I think?

2024-11-07 21:03 UTC, npm1 commented on spec/index.bs
> +            1. If that returned success, go back to the [=fetch accounts step=].
ditto otherwise

2024-11-07 21:18 UTC, cbiesinger commented on spec/index.bs
> +                1. Otherwise, let |permission| be the result of running [=request permission to sign-up=]
The current Chrome implementation and IMO the better experience is not to terminate the flow in this situation.

2024-11-07 21:18 UTC, cbiesinger commented on spec/index.bs
> +        1. If that returned success, go back to the [=fetch accounts step=].
Ditto

2024-11-07 21:18 UTC, cbiesinger commented on spec/index.bs
> +            1. If that returned success, go back to the [=fetch accounts step=].
Ditto

2024-11-07 21:39 UTC, npm1 approved these changes
lgtm with nit

2024-11-07 21:39 UTC, npm1 commented on spec/index.bs
> +                the account chooser MUST provide an affordance to use another account. If that
this indentation is confusing, this is supposed to be part of the current statement so should not be indented more. But actually I think it is cleaner to use a separate statement for this. To do that we need to move the 'show a dialog' to an inner statement
```
1. If compute returns connected:
  1. Show a dialog
  1. If support_use_other_account
1. Otherwise, ...
```

2024-11-07 21:46 UTC, cbiesinger commented on spec/index.bs
> +                the account chooser MUST provide an affordance to use another account. If that
Thanks, done.

2024-11-08 20:00 UTC, TallTed requested changes

2024-11-08 20:00 UTC, TallTed commented on spec/index.bs
> +                1. [=Show an IDP login dialog=] with |config|, |provider| and |globalObject|.
```suggestion
                1. [=Show an IDP login dialog=] with |config|, |provider|, and |globalObject|.
```

2024-11-08 20:00 UTC, TallTed commented on spec/index.bs
>      1. Assert: These steps are running [=in parallel=].
The parallel steps would be better presented as bullets (which might bullets within a numbered step), rather than as numbered steps. As this stands, I am unsure exactly *which* steps are `running in parallel`.

2024-11-08 20:00 UTC, TallTed commented on spec/index.bs
> +            1. [=Show an IDP login dialog=] with |config|, |provider| and |globalObject|.
```suggestion
            affordance was provided in a previous step (e.g., if [=select an account=] was
            invoked). If that affordance is triggered:
            1. [=Show an IDP login dialog=] with |config|, |provider|, and |globalObject|.
```

2024-11-20 02:17 UTC, domenic commented on spec/index.bs
>      1. Assert: These steps are running [=in parallel=].
This would not be correct. Please check the definition of "in parallel": https://html.spec.whatwg.org/multipage/infrastructure.html#in-parallel

2024-11-21 16:01 UTC, TallTed commented on spec/index.bs
>      1. Assert: These steps are running [=in parallel=].
The definition of "in parallel" is not sufficient for me (and I have some familiarity with the subject) to know whether the numbered steps (1)-(20) of which this Assert is (1) are to run *in parallel* with each other (which appears possible, and indeed, the most likely meaning) *or* that this sequence of 20 steps is to occur *in parallel* with other operations (sequences, single steps, etc.) in the spec.

Presuming that one goal of writing this specification is to have it be comprehensible by readers who are new to the subject, I suggest that some rewording would be helpful.

2024-11-22 05:43 UTC, domenic commented on spec/index.bs
>      1. Assert: These steps are running [=in parallel=].
A PR to the HTML spec is welcome, but I think it's pretty clear personally:

> means those steps are to be run, one after another

2024-11-22 21:42 UTC, TallTed commented on spec/index.bs
>      1. Assert: These steps are running [=in parallel=].
"In parallel" does not mean "in sequence", no matter what spec is written as if it does.

Also, I highly doubt that most readers of this spec will go to the HTML spec, so while I may well submit a PR there (if I can find where to do so; it wasn't obvious when I looked for it yesterday), I think it better to provide more clarity in the FedCM spec.

2024-11-22 23:39 UTC, cbiesinger commented on spec/index.bs
>      1. Assert: These steps are running [=in parallel=].
For better or worse, "in parallel" is an existing term in specland. Ted, do you have a specific suggestion for how to improve this?

In general we should assume that readers either know what these terms mean or click through to their definition, IMO.

2024-11-22 23:40 UTC, cbiesinger commented on spec/index.bs
>      1. Assert: These steps are running [=in parallel=].
(https://github.com/whatwg/html/blob/main/source is where you would send PRs for the HTML spec)

2024-11-25 17:14 UTC, TallTed commented on spec/index.bs
>      1. Assert: These steps are running [=in parallel=].
Unfortunately, GitHub's web interface (my primary tool) can't handle docs the size of that WHATWG source. But, I was able to view it, and noted the "parallel queue".
```
<p>A <dfn export>parallel queue</dfn> represents a queue of algorithm steps that must be run in 
series.</p>
```
I think that's a more apt description of this 20-step sequence. Something like 
```suggestion
    1. Assert: These steps comprise a [=parallel queue=] that should run [=in parallel=] with any other active algorithms and/or [=parallel queues=].
```
(That does presume that plurals of defined terms are properly handled; the last might need change from `[=parallel queues=]` to `[=parallel queue=]`.)

2024-11-25 17:16 UTC, TallTed commented on spec/index.bs
> +            {{IdentityCredentialRequestOptions/context}} and |options|'s
Should this not be as above (lines 909–910), i.e., —
```suggestion
        1. The user agent MAY use the |options|'s
            {{IdentityCredentialRequestOptions/context}} and |options|'s
```

2024-11-26 16:45 UTC, hlflanagan commented
Discussed on https://github.com/fedidcg/meetings/blob/main/2024/2024-11-26-notes.md. Needs further review.

2024-11-26 20:40 UTC, TallTed commented on spec/index.bs
>      1. Assert: These steps are running [=in parallel=].
@domenic — Your thumb-down emoji doesn't communicate even as well as the "in parallel" that is meant to be understood as some language other than English. If you have an argument against my points, please do me the courtesy of writing it out.

2025-01-14 16:59 UTC, wseltzer commented
Discussed at January 14, 2025 meeting [minutes]

2025-02-05 19:50 UTC, bvandersloot-mozilla commented
Why does this behavior need to be gated behind an IDP opt in?

2025-02-05 19:55 UTC, cbiesinger commented
> Why does this behavior need to be gated behind an IDP opt in?

As mentioned in one of the meetings, some IDPs do not support multiple accounts for one person so this would not be useful for them.

2025-02-05 20:13 UTC, TallTed commented on spec/index.bs
>      1. Assert: These steps are running [=in parallel=].
I am at a loss. @domenic, you are not participating usefully. Please refrain from emoting unexplained "thumb down". If you have an argument against what I've said, please put into words, so I and others can consider your point(s) against my own.

2025-02-05 20:15 UTC, bvandersloot-mozilla commented
Follow up: is there a reason it varies between active and passive if it is expected to be per-IDP?

2025-03-06 15:59 UTC, cbiesinger commented
We are happy to make this a single toplevel boolean `supports_use_other_account`. I will update the PR accordingly.

2025-03-13 19:16 UTC, cbiesinger commented on spec/index.bs
> +            {{IdentityCredentialRequestOptions/context}} and |options|'s
Because I am not touching those lines (anymore), I do not want to change that as part of this PR but I can do that separately.

2025-03-13 19:17 UTC, cbiesinger commented
@bvandersloot-mozilla @npm1 please take another look, I have updated the PR to use a single toplevel boolean.

2025-03-13 19:24 UTC, cbiesinger commented on spec/index.bs
> +            {{IdentityCredentialRequestOptions/context}} and |options|'s
Actually, that algorithm does not have an |options| parameter, so this is not a simple change.

2025-03-17 21:44 UTC, npm1 commented on spec/index.bs
> +                1. If that returned success, go back to the [=fetch accounts step=].
Should there be an otherwise here?

2025-03-17 21:46 UTC, npm1 commented on spec/index.bs
> +        1. If that returned success, go back to the [=fetch accounts step=].
Should there be an otherwise here?

2025-03-17 21:49 UTC, npm1 commented on spec/index.bs
> +            1. If |supportsUseOtherAccount| is true, the account chooser MUST
I wonder if this should instead be covered by showing an initial step to select an account if this is true, otherwise go direct to request permission?

2025-03-19 19:29 UTC, cbiesinger commented on spec/index.bs
> +                1. If that returned success, go back to the [=fetch accounts step=].
Done

2025-03-19 19:29 UTC, cbiesinger commented on spec/index.bs
> +        1. If that returned success, go back to the [=fetch accounts step=].
Done.

2025-03-19 19:30 UTC, cbiesinger commented on spec/index.bs
> +            1. If |supportsUseOtherAccount| is true, the account chooser MUST
You're suggesting that we should require showing the account chooser first if "supports use other account" is true, even if there is only one account signed in to the IDP?

2025-03-20 19:02 UTC, npm1 commented on spec/index.bs
> +            1. If |supportsUseOtherAccount| is true, the account chooser MUST
Yea... that matches the Chrome implementation (for active mode which the only case we are keeping anyways)

2025-03-25 15:59 UTC, bvandersloot-mozilla commented on spec/index.bs
> +            1. If |supportsUseOtherAccount| is true, the account chooser MUST
That sounds reasonable to me.

2025-06-10 22:32 UTC, cbiesinger commented on spec/index.bs
> +            1. If |supportsUseOtherAccount| is true, the account chooser MUST
Done.

2025-06-11 18:14 UTC, npm1 commented on spec/index.bs
> +                1. If |result| is failure, go back to [=show accounts=].
This is not 'back', this step is after. Is this right?

2025-06-11 18:14 UTC, npm1 commented on spec/index.bs
> +                1. Otherwise, go back to the [=fetch accounts step=] to get an updated
Hmm I guess this works in that this feature only works in the spec currently with a single account, but we would need to make this cleaner when we add multi IDP support I think.

2025-06-11 18:14 UTC, npm1 commented on spec/index.bs
> +                1. Otherwise, go back to the account chooser.
What is the 'account chooser'?

2025-06-11 18:45 UTC, cbiesinger commented on spec/index.bs
> +                1. If |result| is failure, go back to [=show accounts=].
Eh. Because this gets triggered by user action at a later point, it is going back temporally. But I've removed the "back" here.

2025-06-11 18:47 UTC, cbiesinger commented on spec/index.bs
> +                1. Otherwise, go back to the [=fetch accounts step=] to get an updated
Yeah maybe. Possibly something else should be labelled "fetch accounts step". Anyway I'll resolve this since it sounds you are fine with this for now.

2025-06-11 18:49 UTC, cbiesinger commented on spec/index.bs
> +                1. Otherwise, go back to the account chooser.
The thing mentioned on line 998, right above (which I just noticed is not a grammatically correct sentence). But OK, I added a dfn and a link to the dfn.

2025-06-11 21:27 UTC, npm1 approved these changes
lgtm. Awaiting review from Ben/Mozilla

2025-06-12 15:13 UTC, cbiesinger commented on spec/index.bs
>      1. Assert: These steps are running [=in parallel=].
I am going to resolve this thread because this PR no longer touches that section and "in parallel" was largely orthogonal to this change anyway.

2025-06-17 15:08 UTC, bvandersloot-mozilla commented on spec/index.bs
> +            1. If |supportsUseOtherAccount| is true, the account chooser MUST provide
```suggestion
            1. If |supportsUseOtherAccount| is true, the account chooser SHOULD provide
```
This seems a bit better, but feel free to drop it.

2025-06-17 16:08 UTC, cbiesinger commented
Thanks, done. @npm1 I think this is ready to merge!

2025-06-17 16:12 UTC, merged