Add single-get multi IDP support for passive mode
w3c-fedid/FedCM pull request #686
Opened 2024-12-10 19:57 UTC by npm1

2025-01-13 22:01 UTC, npm1 commented
ptal

2025-01-14 18:35 UTC, TallTed requested changes

2025-01-14 18:35 UTC, TallTed commented on spec/index.bs
> +            same time, e.g. the second [=IDP=]'s fetches can be started before the first ones finish,
```suggestion
            same time, e.g., the second [=IDP=]'s fetches can be started before the first ones finish,
```

2025-01-14 18:35 UTC, TallTed commented on spec/index.bs
> +            1. Otherwise, set |providerMap|[|providerOrigin|] to "logged-out" and [=continue=].
`set |providerMap|[|providerOrigin|] to` appears to be incorrect markup or punctuation, though similar occurs a few times (also flagged, below) in this PR.

It results in 
> set _providerMap_[_providerOrigin_] to

I'm not familiar enough with `.bs` to correct it.

2025-01-14 18:35 UTC, TallTed commented on spec/index.bs
> +                |providerMap|[|providerOrigin|] to "mismatch" and [=continue=].
Again, `set |providerMap|[|providerOrigin|] to` appears likely to be incorrect markup or punctuation.

2025-01-14 18:35 UTC, TallTed commented on spec/index.bs
> +                the picture.
Again, `If |acc|["{{IdentityProviderAccount/picture}}"] is` appears likely to be incorrect markup or punctuation.

2025-01-14 18:35 UTC, TallTed commented on spec/index.bs
> +                based on which fetches occurred.
I think this is intended to be within the immediately preceding (1), not its parent, so it wants more indent.
```suggestion
               Note: We require downloading the pictures here before we potentially filter the account
                   list so that the identity provider cannot determine what hints were provided
                   based on which fetches occurred.
```

2025-01-14 20:29 UTC, npm1 commented on spec/index.bs
> +            same time, e.g. the second [=IDP=]'s fetches can be started before the first ones finish,
done

2025-01-14 20:30 UTC, npm1 commented on spec/index.bs
> +                based on which fetches occurred.
done

2025-01-14 22:15 UTC, cbiesinger commented on spec/index.bs
> -    1. If the [=list/size=] of
Shouldn't this algorithm still check that the list is not empty?

2025-01-14 22:18 UTC, cbiesinger commented on spec/index.bs
> +        Note: The fetches performed in these steps to populate |providerMap| can be peformed at the
peformed -> performed

2025-01-14 22:30 UTC, cbiesinger commented on spec/index.bs
> +            1. <dfn>Mismatch dialog step</dfn>: If |loginStatus| is [=logged-in=], set
Hmm this `<dfn>` has to move somewhere else I think? I don't think the "goto the mismatch dialog step" references will be right otherwise (an infinite loop?).

Alternatively, maybe those places can just directly set map[origin] to mismatch

2025-01-14 22:34 UTC, cbiesinger commented on spec/index.bs
> +    1. The user agent will now create a prompt to the user by building on the values from |providerMap|.
I can't tell, is this an informal note describing what the next steps do, or something normative?

2025-01-14 22:43 UTC, cbiesinger commented on spec/index.bs
> +        1. Otherwise, if |value| is "mismatch", add contents indicating this [=IDP=]
The new phrasing seems a bit odd (what does "indicating this IDP" mean here?)

2025-01-14 22:45 UTC, cbiesinger commented on spec/index.bs
> +                * If the user selects another option, do nothing.
What other option...?

2025-01-14 22:47 UTC, cbiesinger commented on spec/index.bs
> +                    dialog to request user permission to sign in via |selectedAccount|, and set the
This is not right, because there may be more accounts in the other IDPs.

Is this section assuming that `value` is a list of accounts from all IDPs combined? That is not what the algorithm does, and it is incorrect even if so because you should not go directly to request permission if some IDPs are in mismatch state (right?)

2025-01-15 18:56 UTC, npm1 commented on spec/index.bs
> +            1. <dfn>Mismatch dialog step</dfn>: If |loginStatus| is [=logged-in=], set
I think it still works but the goto is not really needed anymore so I removed this dfn and made the actual thing explicit since it's clearer.

2025-01-15 18:56 UTC, npm1 commented on spec/index.bs
> +    1. The user agent will now create a prompt to the user by building on the values from |providerMap|.
It is informative. Since it is confusing I removed it

2025-01-15 18:56 UTC, npm1 commented on spec/index.bs
> +        1. Otherwise, if |value| is "mismatch", add contents indicating this [=IDP=]
Changed to `|providerOrigin|`

2025-01-15 18:56 UTC, npm1 commented on spec/index.bs
> +                * If the user selects another option, do nothing.
Any other UI option. I simplified this to only mention what happens if this option is selected for each UI option.

2025-01-15 18:56 UTC, npm1 commented on spec/index.bs
> +                    dialog to request user permission to sign in via |selectedAccount|, and set the
Yea they are combined. Made this more explicit and added the mismatch condition

2025-01-16 21:10 UTC, cbiesinger commented on spec/index.bs
> +            1. Set |selectedAccount| to the result of running the [=select an account=] from |allAccounts|.
There is a bit of a mismatch between the algorithm here and "select an account". The latter displays an account chooser, but you already built UI here.

I am actually not sure that "select an account" is still useful. It is a pretty short algorithm and you already have the UI built here. So maybe this should just be "Wait for the user to select an account" or something, and then set |selectedAccount| acccordingly.

2025-01-16 21:10 UTC, cbiesinger commented on spec/index.bs
> +    1. Also include an affordance to close the dialog. If the user closes this dialog, return (failure,
This should probably be before "1. If |allAccounts| is not [=list/empty=], add UI to present the account options to the user as follows:", because those steps have various things that wait for user input.

2025-01-16 22:13 UTC, npm1 commented on spec/index.bs
> +            1. Set |selectedAccount| to the result of running the [=select an account=] from |allAccounts|.
Ok, moved it here and fixed the issue

2025-01-16 22:13 UTC, npm1 commented on spec/index.bs
> +    1. Also include an affordance to close the dialog. If the user closes this dialog, return (failure,
I think there I've removed waits in the previous steps. What there are are steps that are to be executed if a certain UI selection is made by the user, which is covered by the wait in the following step.

2025-01-16 22:26 UTC, cbiesinger commented on spec/index.bs
> +    1. Also include an affordance to close the dialog. If the user closes this dialog, return (failure,
In the size 1 case, a wait is implied in "request permission to sign up" (because it returns an account), and `show a dialog to request user permission to sign in via |selectedAccount|, and set the result in |permission|` also implies a wait

2025-01-17 15:30 UTC, npm1 commented on spec/index.bs
> +    1. Also include an affordance to close the dialog. If the user closes this dialog, return (failure,
Oh yes I see what you mean. Moved up

2025-01-21 19:05 UTC, wseltzer commented
Discussed at Jan 21, 2025 meeting [minutes](https://github.com/fedidcg/meetings/blob/main/2025/2025-01-21-notes.md#notes).

2025-01-21 21:33 UTC, cbiesinger commented on spec/index.bs
> +            1. Assert |allAccounts|'s [=list/size=] is greater than 1.
I actually think this assert is wrong -- it is possible that size==1 if providerMap contains mismatch

2025-01-21 21:33 UTC, cbiesinger commented on spec/index.bs
> +            1. If the user selects an account, perform the following steps:
this needs an else?

2025-01-21 21:33 UTC, cbiesinger commented on spec/index.bs
> +                1. Let |selectedAccount| be the {{IdentityProviderAccount}} chosen.
does this have to be "Set" instead of let? AIUI Let is only for declaring variables.

2025-01-21 23:05 UTC, TallTed requested changes

2025-01-21 23:05 UTC, TallTed commented on spec/index.bs
>          closed, if any are created in the previous steps.
```suggestion
    1. If [=user agent=] created any dialogs requesting user choice or permission in the previous steps,
        wait until they are closed.
```

2025-01-23 15:44 UTC, npm1 commented on spec/index.bs
> +            1. If the user selects an account, perform the following steps:
The 'else' would be handled by the wait until the dialog is closed

2025-01-23 18:14 UTC, cbiesinger approved these changes

2025-01-23 18:14 UTC, cbiesinger commented on spec/index.bs
> +            1. If the user selects an account, perform the following steps:
In that case, you need to do something about the assert on line 958

2025-01-23 18:35 UTC, npm1 commented on spec/index.bs
> +            1. If the user selects an account, perform the following steps:
Ah yea needs to go after the permission check, thanks.

2025-02-05 20:08 UTC, bvandersloot-mozilla commented
This overall seems reasonable, but raises questions for me about how a browser with an IDP picker integrates with the spec. Right now it works with single IDP, however, I think that I want to be able to show account information in the IDP picker where there is already a linkage.  

How does this handle where a response is in the connected account set? Does it still show the dialog?

2025-02-06 20:47 UTC, npm1 commented
Hey Ben, sorry not sure I follow your questions but trying to answer:

> I think that I want to be able to show account information in the IDP picker where there is already a linkage.

Regarding IDP picker with account information: sure, this is intended to be allowed. You can show any UI before fetching the accounts, so in particular you can show UI using some information that you cache from an account in the connected accounts set. However, I do worry that this effectively removes auto reauthentication since you can only really know the returning accounts after fetching. You could guess when it may happen based on the connected accounts set but that seems brittle.

> How does this handle where a response is in the connected account set? Does it still show the dialog?

Not sure I follow. If there are accounts in the connected account set, this just means it may be possible to perform auto reauthentication. Of course, the user agent is encouraged to nudge the user towards these accounts as well as accounts whose `approved_clients` imply that this is an IDP account that has already been previously used to login to the RP. But in general, unless there is exactly one account in the connected accounts set AND the RP requests auto reauthentication, then the IDP should try to perform the login automatically, whereas in any other case we let the user confirm the account they wish to use first.

2025-02-10 16:25 UTC, cbiesinger commented
@bvandersloot-mozilla is your question maybe this: does the algorithm allow fetching and displaying accounts only from IDPs who have accounts in the connected set, and only showing the IDP name for the other IDPs (fetching accounts once you click that)?

2025-02-14 16:59 UTC, bvandersloot-mozilla commented
@cbiesinger, that is precisely what I meant, thanks!

2025-02-19 17:09 UTC, npm1 commented
Added support for this (during the wait, the user agent may set the provider list to a subset of itself)

2025-03-18 16:21 UTC, npm1 commented
Ping @bvandersloot-mozilla. Let me know if you want me to add active mode support here as well or any other comments so I can merge this

2025-03-24 16:36 UTC, bvandersloot-mozilla commented
It seems like we should add active multi-idp, however this is probably reasonable to merge as is

2025-03-25 14:24 UTC, merged

2025-03-25 15:51 UTC, wseltzer commented
Discussed [March 25](https://github.com/w3c-fedid/meetings/blob/main/2025/2025-03-25-notes.md)